dist: trusty
language: node_js
node_js:
  - 10
  - 8
  - 12

install: npm install

script:
  - npm run test
  - npm run build
  - npm run doc

after_success:
  - echo 'node_modules' > .gitignore
  - echo $CNAME > CNAME

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
    node: "8"
